### ISSUE TITLE
android error

### ISSUE THREAD

**Issue by bFlood** [eclipsesource/tabris-maps#3]
this is probably map key related but I'm now seeing this error on debug and production builds (created new keystore and google api key as well). Has anything changed on the Tabris build servers with reagrd to Google Play Services?

``` java
 10-05 15:59:56.075: E/AndroidRuntime(10154): FATAL EXCEPTION: main
10-05 15:59:56.075: E/AndroidRuntime(10154): Process: com.sdlportal.sdlmobile3, PID: 10154
10-05 15:59:56.075: E/AndroidRuntime(10154): java.lang.NoSuchMethodError: No static method zzch(Ljava/lang/String;)V in class Lcom/google/android/gms/common/internal/zzx; or its super classes (declaration of 'com.google.android.gms.common.internal.zzx' appears in /data/app/com.sdlportal.sdlmobile3-1/base.apk)
10-05 15:59:56.075: E/AndroidRuntime(10154):    at com.google.android.gms.maps.MapFragment.getMapAsync(Unknown Source)
10-05 15:59:56.075: E/AndroidRuntime(10154):    at com.eclipsesource.tabris.maps.MapHolderView.setOnMapReadyListener(MapHolderView.java:61)
10-05 15:59:56.075: E/AndroidRuntime(10154):    at com.eclipsesource.tabris.maps.MapOperator$2.run(MapOperator.java:72)
10-05 15:59:56.075: E/AndroidRuntime(10154):    at android.os.Handler.handleCallback(Handler.java:739)
10-05 15:59:56.075: E/AndroidRuntime(10154):    at android.os.Handler.dispatchMessage(Handler.java:95)
10-05 15:59:56.075: E/AndroidRuntime(10154):    at android.os.Looper.loop(Looper.java:145)
10-05 15:59:56.075: E/AndroidRuntime(10154):    at android.app.ActivityThread.main(ActivityThread.java:5974)
10-05 15:59:56.075: E/AndroidRuntime(10154):    at java.lang.reflect.Method.invoke(Native Method)
10-05 15:59:56.075: E/AndroidRuntime(10154):    at java.lang.reflect.Method.invoke(Method.java:372)
10-05 15:59:56.075: E/AndroidRuntime(10154):    at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:1388)
10-05 15:59:56.075: E/AndroidRuntime(10154):    at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1183)
```

also, the build log I'm seeing this entry as well. is this a possible conflict with differing Google Play Services versions?
`:prepareComGoogleAndroidGmsPlayServicesBase810Library
:prepareComGoogleAndroidGmsPlayServicesBasement810Library
:prepareComGoogleAndroidGmsPlayServicesGcm810Library
:prepareComGoogleAndroidGmsPlayServicesMaps780Library`

**Comment by bFlood** [comment]
fwiw, bumping https://github.com/eclipsesource/tabris-maps/blob/master/plugin.xml#L54 to 8.1.0 solved the issue.

**Comment by mpost** [comment]
Good to know that it worked for you. We should also bump to the latest gsm version.
