### ISSUE TITLE
 “Could not get property “myLocation”, on com.eclipsesource.maps.Map (Reason, MyLocation layer not enabled.)

### ISSUE THREAD

**Issue by petertool** [eclipsesource/tabris-maps#38]
On Android, I get the following error when trying to show the user's current location:
 “Could not get property “myLocation”, on com.eclipsesource.maps.Map (Reason, MyLocation layer not enabled.)

- Tabris.js version:  tabris 2.1
- OS: Android only

### Code snippet

```javascript
Log returns “Could not get property “myLocation”, on com.eclipsesource.maps.Map (Reason, MyLocation layer not enabled.)
```

**Comment by cookieguru** [comment]
Am able to reproduce this error on Android 8.0.  The app never asks for the location permission.  Code snippet:
```js
new esmaps.Map({
	left: 0, right: 0, top: 0, bottom: 0,
	showMyLocation: true,
	showMyLocationButton: true,
}).appendTo(tabris.ui.contentView);
```
The button to zoom to the user's location is never displayed/

Logcat:
```plain
10-05 17:19:45.417 22166 22166 D incoming-operation: 'Create' on 'tabris.App' (o1) with properties {}
10-05 17:19:45.417 22166 22166 D incoming-operation: 'Get' on 'tabris.App' (o1) with property 'tabrisJsVersion'
10-05 17:19:45.430 22166 22166 D incoming-operation: 'Create' on 'tabris.Ui' (o2) with properties {}
10-05 17:19:45.431 22166 22166 D incoming-operation: 'Create' on 'tabris.Composite' (o3) with properties {parent=o2, root=true}
10-05 17:19:45.433 22166 22166 D incoming-operation: 'Create' on 'tabris.StatusBar' (o4) with properties {parent=o2}
10-05 17:19:45.433 22166 22166 D incoming-operation: 'Create' on 'tabris.NavigationBar' (o5) with properties {parent=o2}
10-05 17:19:45.434 22166 22166 D incoming-operation: 'Create' on 'tabris.Drawer' (o6) with properties {parent=o2}
10-05 17:19:45.435 22166 22166 D incoming-operation: 'Create' on 'tabris.Device' (o7) with properties {}
10-05 17:19:45.435 22166 22166 D incoming-operation: 'Create' on 'tabris.FileSystem' (o8) with properties {}
10-05 17:19:45.435 22166 22166 D incoming-operation: 'Get' on 'tabris.Device' (o7) with property 'scaleFactor'
10-05 17:19:45.440 22166 22166 D incoming-operation: 'Create' on 'tabris.ClientStore' (o9) with properties {}
10-05 17:19:45.440 22166 22166 D incoming-operation: 'Get' on 'tabris.Device' (o7) with property 'platform'
10-05 17:19:45.448 22166 22166 D incoming-operation: 'Create' on 'tabris.Crypto' (o10) with properties {}
10-05 17:19:45.449 22166 22166 D incoming-operation: 'Create' on 'tabris.Timer' (o11) with properties {delay=5000, repeat=false}
10-05 17:19:45.449 22166 22166 D incoming-operation: 'Listen' on 'tabris.Timer' (o11) with event 'run = true'
10-05 17:19:45.449 22166 22166 D incoming-operation: 'Call' on 'tabris.Timer' (o11) with method 'start' with properties {}
10-05 17:19:45.545 22166 22166 D incoming-operation: 'Listen' on 'tabris.App' (o1) with event 'pause = true'
10-05 17:19:45.545 22166 22166 D incoming-operation: 'Listen' on 'tabris.App' (o1) with event 'resume = true'
10-05 17:19:45.546 22166 22166 D incoming-operation: 'Create' on 'com.eclipsesource.maps.Map' (o12) with properties {showMyLocation=true, showMyLocationButton=true}
10-05 17:19:45.547 22166 22166 W System.err: java.lang.IllegalStateException: android.permission.ACCESS_FINE_LOCATION not available
10-05 17:19:45.547 22166 22166 W System.err: 	at com.eclipsesource.tabris.maps.MapPropertyHandler.setShowMyLocation(MapPropertyHandler.java:130)
10-05 17:19:45.547 22166 22166 W System.err: 	at com.eclipsesource.tabris.maps.MapPropertyHandler.setProperty(MapPropertyHandler.java:82)
10-05 17:19:45.547 22166 22166 W System.err: 	at com.eclipsesource.tabris.maps.MapPropertyHandler.set(MapPropertyHandler.java:63)
10-05 17:19:45.548 22166 22166 W System.err: 	at com.eclipsesource.tabris.maps.MapPropertyHandler.set(MapPropertyHandler.java:28)
10-05 17:19:45.548 22166 22166 W System.err: 	at com.eclipsesource.tabris.android.internal.OperationDispatcher.invokeSetOnPropertyHandler(OperationDispatcher.java:58)
10-05 17:19:45.548 22166 22166 W System.err: 	at com.eclipsesource.tabris.android.internal.OperationDispatcher.create(OperationDispatcher.java:42)
10-05 17:19:45.548 22166 22166 W System.err: 	at com.eclipsesource.tabris.android.internal.javascript.NativeBridge.create(NativeBridge.java:41)
10-05 17:19:45.548 22166 22166 W System.err: 	at com.eclipsesource.tabris.android.internal.javascript.V8JavaScriptBridge$6.invoke(V8JavaScriptBridge.java:149)
10-05 17:19:45.548 22166 22166 W System.err: 	at com.eclipsesource.v8.V8.callVoidJavaMethod(V8.java:890)
10-05 17:19:45.548 22166 22166 W System.err: 	at com.eclipsesource.v8.V8._executeVoidFunction(Native Method)
10-05 17:19:45.548 22166 22166 W System.err: 	at com.eclipsesource.v8.V8.executeVoidFunction(V8.java:1133)
10-05 17:19:45.548 22166 22166 W System.err: 	at com.eclipsesource.v8.V8Object.executeVoidFunction(V8Object.java:435)
10-05 17:19:45.548 22166 22166 W System.err: 	at com.eclipsesource.tabris.android.internal.javascript.V8JavaScriptBridge.start(V8JavaScriptBridge.java:197)
10-05 17:19:45.548 22166 22166 W System.err: 	at com.eclipsesource.tabris.android.internal.javascript.JavaScriptBootStrategy.runJavaScript(JavaScriptBootStrategy.java:111)
10-05 17:19:45.549 22166 22166 W System.err: 	at com.eclipsesource.tabris.android.internal.javascript.JavaScriptBootStrategy.run(JavaScriptBootStrategy.java:64)
10-05 17:19:45.549 22166 22166 W System.err: 	at com.eclipsesource.tabris.android.TabrisActivity.bootApp(TabrisActivity.java:110)
10-05 17:19:45.549 22166 22166 W System.err: 	at com.eclipsesource.tabris.android.TabrisActivity.onCreate(TabrisActivity.java:69)
10-05 17:19:45.549 22166 22166 W System.err: 	at android.app.Activity.performCreate(Activity.java:6975)
10-05 17:19:45.549 22166 22166 W System.err: 	at android.app.Instrumentation.callActivityOnCreate(Instrumentation.java:1213)
10-05 17:19:45.549 22166 22166 W System.err: 	at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2770)
10-05 17:19:45.549 22166 22166 W System.err: 	at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2892)
10-05 17:19:45.549 22166 22166 W System.err: 	at android.app.ActivityThread.-wrap11(Unknown Source:0)
10-05 17:19:45.549 22166 22166 W System.err: 	at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1593)
10-05 17:19:45.549 22166 22166 W System.err: 	at android.os.Handler.dispatchMessage(Handler.java:105)
10-05 17:19:45.549 22166 22166 W System.err: 	at android.os.Looper.loop(Looper.java:164)
10-05 17:19:45.550 22166 22166 W System.err: 	at android.app.ActivityThread.main(ActivityThread.java:6541)
10-05 17:19:45.550 22166 22166 W System.err: 	at java.lang.reflect.Method.invoke(Native Method)
10-05 17:19:45.551 22166 22166 W System.err: 	at com.android.internal.os.Zygote$MethodAndArgsCaller.run(Zygote.java:240)
10-05 17:19:45.551 22166 22166 W System.err: 	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:767)
10-05 17:19:45.551 22166 22166 D Tabris  : WARN Could not create object "com.eclipsesource.maps.Map" on com.eclipsesource.maps.Map (Reason: android.permission.ACCESS_FINE_LOCATION not available)
10-05 17:19:45.551 22166 22166 D incoming-operation: 'Listen' on 'com.eclipsesource.maps.Map' (o12) with event 'ready = true'
10-05 17:19:45.553 22166 22166 D incoming-operation: 'Set' on 'com.eclipsesource.maps.Map' (o12) with properties {parent=o3, layoutData=Properties [properties={top=0, left=0, bottom=0, right=0}]}
10-05 17:19:45.559 22166 22166 I Google Maps Android API: Google Play services package version: 11518940
```

After manually enabling the permission, the error changes to
```plain
Could not create object "com.eclipsesource.maps.Map" on com.eclipsesource.maps.Map (Reason: Attempt to invoke virtual method 'void com.google.android.gms.maps.GoogleMap.setMyLocationEnabled(boolean)' on a null object reference)
```
Logcat:
```plain
10-05 17:20:03.836 23024 23024 D incoming-operation: 'Create' on 'com.eclipsesource.maps.Map' (o14) with properties {showMyLocation=true, showMyLocationButton=true}
10-05 17:20:03.838 23024 23024 W System.err: java.lang.IllegalStateException: android.permission.ACCESS_FINE_LOCATION not available
10-05 17:20:03.838 23024 23024 W System.err: 	at com.eclipsesource.tabris.maps.MapPropertyHandler.setShowMyLocation(MapPropertyHandler.java:130)
10-05 17:20:03.838 23024 23024 W System.err: 	at com.eclipsesource.tabris.maps.MapPropertyHandler.setProperty(MapPropertyHandler.java:82)
10-05 17:20:03.838 23024 23024 W System.err: 	at com.eclipsesource.tabris.maps.MapPropertyHandler.set(MapPropertyHandler.java:63)
10-05 17:20:03.839 23024 23024 W System.err: 	at com.eclipsesource.tabris.maps.MapPropertyHandler.set(MapPropertyHandler.java:28)
10-05 17:20:03.839 23024 23024 W System.err: 	at com.eclipsesource.tabris.android.internal.OperationDispatcher.invokeSetOnPropertyHandler(OperationDispatcher.java:58)
10-05 17:20:03.839 23024 23024 W System.err: 	at com.eclipsesource.tabris.android.internal.OperationDispatcher.create(OperationDispatcher.java:42)
10-05 17:20:03.839 23024 23024 W System.err: 	at com.eclipsesource.tabris.android.internal.javascript.NativeBridge.create(NativeBridge.java:41)
10-05 17:20:03.839 23024 23024 W System.err: 	at com.eclipsesource.tabris.android.internal.javascript.V8JavaScriptBridge$6.invoke(V8JavaScriptBridge.java:149)
10-05 17:20:03.839 23024 23024 W System.err: 	at com.eclipsesource.v8.V8.callVoidJavaMethod(V8.java:890)
10-05 17:20:03.839 23024 23024 W System.err: 	at com.eclipsesource.v8.V8._executeVoidFunction(Native Method)
10-05 17:20:03.839 23024 23024 W System.err: 	at com.eclipsesource.v8.V8.executeVoidFunction(V8.java:1133)
10-05 17:20:03.839 23024 23024 W System.err: 	at com.eclipsesource.v8.V8Object.executeVoidFunction(V8Object.java:435)
10-05 17:20:03.839 23024 23024 W System.err: 	at com.eclipsesource.tabris.android.internal.javascript.V8JavaScriptBridge.start(V8JavaScriptBridge.java:197)
10-05 17:20:03.839 23024 23024 W System.err: 	at com.eclipsesource.tabris.android.internal.javascript.JavaScriptBootStrategy.runJavaScript(JavaScriptBootStrategy.java:111)
10-05 17:20:03.839 23024 23024 W System.err: 	at com.eclipsesource.tabris.android.internal.javascript.JavaScriptBootStrategy.run(JavaScriptBootStrategy.java:64)
10-05 17:20:03.839 23024 23024 W System.err: 	at com.eclipsesource.tabris.android.TabrisActivity.bootApp(TabrisActivity.java:110)
10-05 17:20:03.839 23024 23024 W System.err: 	at com.eclipsesource.tabris.android.TabrisActivity.onCreate(TabrisActivity.java:69)
10-05 17:20:03.839 23024 23024 W System.err: 	at android.app.Activity.performCreate(Activity.java:6975)
10-05 17:20:03.840 23024 23024 W System.err: 	at android.app.Instrumentation.callActivityOnCreate(Instrumentation.java:1213)
10-05 17:20:03.840 23024 23024 W System.err: 	at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2770)
10-05 17:20:03.840 23024 23024 W System.err: 	at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2892)
10-05 17:20:03.840 23024 23024 W System.err: 	at android.app.ActivityThread.-wrap11(Unknown Source:0)
10-05 17:20:03.840 23024 23024 W System.err: 	at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1593)
10-05 17:20:03.840 23024 23024 W System.err: 	at android.os.Handler.dispatchMessage(Handler.java:105)
10-05 17:20:03.840 23024 23024 W System.err: 	at android.os.Looper.loop(Looper.java:164)
10-05 17:20:03.840 23024 23024 W System.err: 	at android.app.ActivityThread.main(ActivityThread.java:6541)
10-05 17:20:03.840 23024 23024 W System.err: 	at java.lang.reflect.Method.invoke(Native Method)
10-05 17:20:03.840 23024 23024 W System.err: 	at com.android.internal.os.Zygote$MethodAndArgsCaller.run(Zygote.java:240)
10-05 17:20:03.840 23024 23024 W System.err: 	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:767)
10-05 17:20:03.840 23024 23024 D Tabris  : WARN Could not create object "com.eclipsesource.maps.Map" on com.eclipsesource.maps.Map (Reason: android.permission.ACCESS_FINE_LOCATION not available)
10-05 17:20:03.841 23024 23024 D incoming-operation: 'Listen' on 'com.eclipsesource.maps.Map' (o14) with event 'ready = true'
10-05 17:20:03.842 23024 23024 D incoming-operation: 'Set' on 'com.eclipsesource.maps.Map' (o14) with properties {parent=o13}
```

**Comment by cookieguru** [comment]
However, this works ***once the permission is manually granted***:
```js
let map = new esmaps.Map({
	left: 0, right: 0, top: 0, bottom: 0,
}).on('ready', () => {
	map.showMyLocation = true;
	map.showMyLocationButton = true;
	console.log(map.myLocation); //null
	setTimeout(() => {
		console.log(map.myLocation); //works
	}, 250);
}).appendTo(tabris.ui.contentView);
```
If the permission was not manually granted, the `IllegalStateException` is thrown again.

---

Seems there should be an event that broadcast on the JS side that a fix was successful, but I don't see anything that could be listened to:
```plain
10-05 17:42:14.415 23848 23848 D incoming-operation: 'Get' on 'com.eclipsesource.maps.Map' (o12) with property 'myLocation'
10-05 17:42:14.419 23848 23848 D Tabris  : LOG null
10-05 17:42:14.420 23848 23848 D incoming-operation: 'Create' on 'tabris.Timer' (o13) with properties {delay=250, repeat=false}
10-05 17:42:14.421 23848 23848 D incoming-operation: 'Listen' on 'tabris.Timer' (o13) with event 'run = true'
10-05 17:42:14.421 23848 23848 D incoming-operation: 'Call' on 'tabris.Timer' (o13) with method 'start' with properties {}
10-05 17:42:14.425 23848 23848 W ResourceType: Invalid package identifier when getting bag for resource number 0x0000d284
10-05 17:42:14.448   902   955 I ActivityManager: Displayed com.timbond.redacted/com.eclipsesource.tabris.android.TabrisActivity: +1s77ms
10-05 17:42:14.490 23848 23848 D CordovaActivity: Stopped the activity.
10-05 17:42:14.504   902 13798 I GnssLocationProvider: WakeLock acquired by sendMessage(SET_REQUEST, 0, com.android.server.location.GnssLocationProvider$GpsRequest@da10204)
10-05 17:42:14.505   902   940 I GnssLocationProvider: WakeLock released by handleMessage(SET_REQUEST, 0, com.android.server.location.GnssLocationProvider$GpsRequest@da10204)
10-05 17:42:14.674 23848 23848 D outgoing-operation: 'Notify' o13 of 'run' with arguments {}
10-05 17:42:14.676 23848 23848 D incoming-operation: 'Get' on 'com.eclipsesource.maps.Map' (o12) with property 'myLocation'
10-05 17:42:14.692 23848 23848 D Tabris  : INFO [ 47.6204232, -122.3493552 ]
10-05 17:42:14.695 23848 23848 D incoming-operation: 'Destroy' on 'tabris.Timer' (o13)
```

**Comment by mpost** [comment]
Thanks for looking into this.

As a best practice approach you should ask the user to give location permission before showing the map. Thereby he will be able to use it as expected.

You can request the location permission with eg the https://github.com/NeoLSN/cordova-plugin-android-permissions plugin.

**Comment by cpetrov** [comment]
Closing this issue as resolved. Please reopen if you still have issues.
